language: node_js
node_js:
- 10
env:
- version=6
- version=8
- version=10
- version=lts
- version=latest
services:
- docker
script:
- if [[ "$TRAVIS_BRANCH" == "main"  ||  "$TRAVIS_BRANCH" == "travis" ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
  fi
- make test-docker
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
- git reset HEAD --hard
deploy:
- provider: script
  script: lerna publish from-package --yes --no-verify-access
  skip_cleanup: true
  on:
    tags: true
    condition: "$version = 10"
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: ArC04W9wjgu0Mk7sJOFcJoWb7yVS1Pe48I9Y0gV+gg3o/S61NZWF7e7qvNTwE7S8bfL7fQibrcFxoewiwp7zwi+huD+p5uyhKVxS7ee0BRqzjFVDlz66lJ1jrqZAvNtcrEP17YtAE/EZuQ2VCBUmbX9if5XTloCzYeMQZUrYkZs=
